language: cpp
branches:
  only:
    - master
    - /\d+\.\d+\..+/
compiler:
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libeigen3-dev cython python-numpy libqt4-dev libxmu-dev freeglut3-dev libqt4-opengl-dev
script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release -D ALWAYS_BUILD_DOCUMENTATION=True -D EXCLUDE_TESTS_FROM_ALL=False ..
  - make
  - make python_extension
  - test/TestSuite
branches:
  only:
    - master
notifications:
  recipients:
    - afabisch@informatik.uni-bremen.de
  email:
    on_success: change
    on_failure: always
